---
- name: show run
  hosts: ciscos
  gather_facts: no
  tasks:
    - name: show run
      ios_command:
        commands:
          - show run
      register: config
    - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}"
        dest: "{{ file }}"
